/* Generated on: 2025-06-14 21:09:12 */
// clang-format off
"NtCharsetRange",
"NtGrammarProperty",
"NtNonterminalChoices",
"NtNonterminalDefinition",
"NtNonterminalExpression",
"NtNonterminalParameter",
"NtNonterminalProduction",
"NtNonterminalSequence",
"NtRepetitionExpression",
"NtRepetitionRange",
"NtSequenceModifier",
"NtTerminalCharset",
"NtTerminalChoices",
"NtTerminalDefinition",
"NtTerminalDefinitionPair",
"NtTerminalExpression",
"NtTerminalParameter",
"NtTerminalProduction",
"NtTerminalSequence",
"TkBooleanLiteral",
"TkEpsilon",
"TkGrammarPropertyComment",
"TkGrammarPropertyNewline",
"TkGrammarPropertyStart",
"TkGrammarPropertyWhitespace",
"TkIntegerLiteral",
"TkKwParameterHide",
"TkKwParameterId",
"TkKwParameterMerge",
"TkKwParameterUnpack",
"TkNonterminalIdentifier",
"TkPermute",
"TkPlus",
"TkQuestion",
"TkStar",
"TkStringLiteral",
"TkTerminalIdentifier",
"TkTilde",

// clang-format on 