/* Generated on: 2025-06-22 18:10:34 */
// clang-format off
"NtAdvancedExpression",
"NtCharsetRange",
"NtGrammarProperty",
"NtNonterminalChoices",
"NtNonterminalDefinition",
"NtNonterminalExpression",
"NtNonterminalProduction",
"NtNonterminalSequence",
"NtParameterDisplayName",
"NtParameterHide",
"NtParameterId",
"NtParameterMerge",
"NtParameterUnpack",
"NtRepetitionExpression",
"NtRepetitionRange",
"NtTerminalCharset",
"NtTerminalChoices",
"NtTerminalDefinition",
"NtTerminalDefinitionPair",
"NtTerminalExpression",
"NtTerminalProduction",
"NtTerminalSequence",
"TkBooleanLiteral",
"TkEpsilon",
"TkGrammarPropertyComment",
"TkGrammarPropertyNewline",
"TkGrammarPropertyStart",
"TkGrammarPropertyWhitespace",
"TkIdStringLiteral",
"TkIntegerLiteral",
"TkKwParameterDisplayName",
"TkKwParameterHide",
"TkKwParameterId",
"TkKwParameterMerge",
"TkKwParameterUnpack",
"TkNonterminalIdentifier",
"TkPermute",
"TkPermuteDelimited",
"TkPlus",
"TkQuestion",
"TkStar",
"TkStringLiteral",
"TkTerminalIdentifier",
"TkTilde",

// clang-format on 