/* Generated on: 2026-01-12 21:30:54 */
// clang-format off
"Repetition",
"Hidden",
"Sequence",
"Choices",
"Production",
"Charset",
"ParameterMerge",
"Definition",
"ParameterHide",
"ParameterUnpack",
"ParameterDisplayName",
"ParameterId",
"CharsetRange",
"GrammarProperty",
"Identifier",
"Epsilon",
"RepetitionRange",
"GrammarPropertyStart",
"StringLiteral",
"Comma",
"Plus",
"Question",
"Star",
"IntegerLiteral",
"CharacterLiteral",
"IdStringLiteral",
"BooleanLiteral",
// clang-format on 