/* Generated on: 2026-01-11 20:36:47 */
// clang-format off
"Sequence",
"Choices",
"Production",
"ParameterMerge",
"Definition",
"ParameterHide",
"ParameterUnpack",
"ParameterDisplayName",
"ParameterId",
"RepetitionExpression",
"CharsetRange",
"GrammarProperty",
"Identifier",
"Expression",
"Epsilon",
"RepetitionRange",
"TerminalCharset",
"Tilde",
"GrammarPropertyStart",
"StringLiteral",
"Comma",
"Plus",
"Question",
"Star",
"IntegerLiteral",
"CharacterLiteral",
"IdStringLiteral",
"BooleanLiteral",
// clang-format on 