/* Generated on: 2026-02-15 20:46:08 */
// clang-format off
"IntegerLiteral",
"ParameterHide",
"BooleanLiteral",
"Plus",
"CharacterLiteral",
"Question",
"ParameterId",
"Star",
"Comma",
"ParameterDisplayName",
"Definition",
"ParameterMerge",
"PositiveLookahead",
"Production",
"StringLiteral",
"ParameterUnpack",
"NegativeLookahead",
"RepetitionRange",
"Eof",
"Any",
"Epsilon",
"IdStringLiteral",
"Identifier",
"Choices",
"Sequence",
"Hidden",
"Repetition",
"Charset",
"CharsetRange",
// clang-format on 