/* Generated on: 2026-02-19 20:26:39 */
// clang-format off
"IntegerLiteral",
"BooleanLiteral",
"Plus",
"CharacterLiteral",
"Question",
"Star",
"Comma",
"Definition",
"StringLiteral",
"NegativeLookahead",
"Production",
"ParameterDisplayName",
"PositiveLookahead",
"RepetitionRange",
"Eof",
"ParameterHide",
"Any",
"Epsilon",
"IdStringLiteral",
"Identifier",
"ParameterId",
"ParameterMerge",
"ParameterUnpack",
"Choices",
"Sequence",
"Hidden",
"Repetition",
"Charset",
"CharsetRange",
// clang-format on 