#include "pmt/parserbuilder/grm_ast.hpp"

#include <stdexcept>

namespace pmt::parserbuilder {
auto GrmAst::id_to_string(pmt::util::parsert::GenericId::IdType id_) -> std::string {
  switch (id_) {
    case TkStringLiteral:
      return "TkStringLiteral";
    case TkIntegerLiteral:
      return "TkIntegerLiteral";
    case TkBooleanLiteral:
      return "TkBooleanLiteral";
    case TkTerminalIdentifier:
      return "TkTerminalIdentifier";
    case TkRuleIdentifier:
      return "TkRuleIdentifier";
    case TkEpsilon:
      return "TkEpsilon";
    case TkPipe:
      return "TkPipe";
    case TkSemiColon:
      return "TkSemiColon";
    case TkEquals:
      return "TkEquals";
    case TkComma:
      return "TkComma";
    case TkDoubleDot:
      return "TkDoubleDot";
    case TkOpenParen:
      return "TkOpenParen";
    case TkCloseParen:
      return "TkCloseParen";
    case TkOpenBrace:
      return "TkOpenBrace";
    case TkCloseBrace:
      return "TkCloseBrace";
    case TkOpenSquare:
      return "TkOpenSquare";
    case TkCloseSquare:
      return "TkCloseSquare";
    case TkOpenAngle:
      return "TkOpenAngle";
    case TkCloseAngle:
      return "TkCloseAngle";
    case TkPlus:
      return "TkPlus";
    case TkStar:
      return "TkStar";
    case TkQuestion:
      return "TkQuestion";
    case TkKwParameterUnpack:
      return "TkKwParameterUnpack";
    case TkKwParameterHide:
      return "TkKwParameterHide";
    case TkKwParameterMerge:
      return "TkKwParameterMerge";
    case TkKwParameterId:
      return "TkKwParameterId";
    case TkKwParameterCaseSensitive:
      return "TkKwParameterCaseSensitive";
    case TkGrammarPropertyStart:
      return "TkGrammarPropertyStart";
    case TkGrammarPropertyWhitespace:
      return "TkGrammarPropertyWhitespace";
    case TkGrammarPropertyComment:
      return "TkGrammarPropertyComment";
    case TkGrammarPropertyCaseSensitive:
      return "TkGrammarPropertyCaseSensitive";
    case NtGrammar:
      return "NtGrammar";
    case NtTerminalProduction:
      return "NtTerminalProduction";
    case NtTerminalParameter:
      return "NtTerminalParameter";
    case NtTerminalDefinition:
      return "NtTerminalDefinition";
    case NtTerminalSequence:
      return "NtTerminalSequence";
    case NtTerminalChoices:
      return "NtTerminalChoices";
    case NtTerminalRepetition:
      return "NtTerminalRepetition";
    case NtTerminalRepetitionRange:
      return "NtTerminalRepetitionRange";
    case NtTerminalRange:
      return "NtTerminalRange";
    case NtRuleProduction:
      return "NtRuleProduction";
    case NtRuleParameter:
      return "NtRuleParameter";
    case NtRuleDefinition:
      return "NtRuleDefinition";
    case NtRuleSequence:
      return "NtRuleSequence";
    case NtRuleChoices:
      return "NtRuleChoices";
    case NtRuleRepetition:
      return "NtRuleRepetition";
    case NtRuleRepetitionRange:
      return "NtRuleRepetitionRange";
    case NtGrammarProperty:
      return "NtGrammarProperty";
    case NtGrammarPropertyWhitespace:
      return "NtGrammarPropertyWhitespace";
    case NtGrammarPropertyComment:
      return "NtGrammarPropertyComment";
    case NtGrammarPropertyCaseSensitive:
      return "NtGrammarPropertyCaseSensitive";
    case NtTerminalDefinitionPairList:
      return "NtTerminalDefinitionPairList";
    case NtTerminalDefinitionPair:
      return "NtTerminalDefinitionPair";
    default:
      throw std::runtime_error("Invalid id");
  }
}
}  // namespace pmt::parserbuilder