#define TOKEN_STRING_LITERAL             1
#define TOKEN_INTEGER_LITERAL            2
#define TOKEN_BOOLEAN_LITERAL            3
#define TOKEN_TERMINAL_IDENTIFIER        4
#define TOKEN_RULE_IDENTIFIER            5
#define TOKEN_EPSILON                    6
#define TOKEN_PIPE                       7
#define TOKEN_SEMICOLON                  8
#define TOKEN_EQUALS                     9
#define TOKEN_COMMA                     10
#define TOKEN_DOUBLE_DOT                11
#define TOKEN_OPEN_PAREN                12
#define TOKEN_CLOSE_PAREN               13
#define TOKEN_OPEN_BRACE                14
#define TOKEN_CLOSE_BRACE               15
#define TOKEN_OPEN_SQUARE               16
#define TOKEN_CLOSE_SQUARE              17
#define TOKEN_OPEN_ANGLE                18
#define TOKEN_CLOSE_ANGLE               19
#define TOKEN_PLUS                      20
#define TOKEN_STAR                      21
#define TOKEN_QUESTION                  22
#define TOKEN_TILDE                     23
#define TOKEN_KW_PARAMETER_UNPACK       24
#define TOKEN_KW_PARAMETER_HIDE         25
#define TOKEN_KW_PARAMETER_MERGE        26
#define TOKEN_KW_PARAMETER_ID           27
#define TOKEN_KW_PARAMETER_CASE_SENSITIVE  28
#define TOKEN_GRAMMAR_PROPERTY_START    29
#define TOKEN_GRAMMAR_PROPERTY_WHITESPACE  30
#define TOKEN_GRAMMAR_PROPERTY_COMMENT  31
#define TOKEN_GRAMMAR_PROPERTY_NEWLINE  32
#define TOKEN_GRAMMAR_PROPERTY_CASE_SENSITIVE  33
