#include "pmt/parserbuilder/grm_ast.hpp"

#include <stdexcept>

namespace pmt::parserbuilder {
auto GrmAst::id_to_string(pmt::util::parsert::GenericId::IdType id_) -> std::string {
  switch (id_) {
    case TkStringLiteral:
      return "TkStringLiteral";
    case TkIntegerLiteral:
      return "TkIntegerLiteral";
    case TkBooleanLiteral:
      return "TkBooleanLiteral";
    case TkTerminalIdentifier:
      return "TkTerminalIdentifier";
    case TkRuleIdentifier:
      return "TkRuleIdentifier";
    case TkEpsilon:
      return "TkEpsilon";
    case TkPipe:
      return "TkPipe";
    case TkSemiColon:
      return "TkSemiColon";
    case TkEquals:
      return "TkEquals";
    case TkComma:
      return "TkComma";
    case TkDoubleDot:
      return "TkDoubleDot";
    case TkOpenParen:
      return "TkOpenParen";
    case TkCloseParen:
      return "TkCloseParen";
    case TkOpenBrace:
      return "TkOpenBrace";
    case TkCloseBrace:
      return "TkCloseBrace";
    case TkOpenSquare:
      return "TkOpenSquare";
    case TkCloseSquare:
      return "TkCloseSquare";
    case TkOpenAngle:
      return "TkOpenAngle";
    case TkCloseAngle:
      return "TkCloseAngle";
    case TkPlus:
      return "TkPlus";
    case TkStar:
      return "TkStar";
    case TkQuestion:
      return "TkQuestion";
    case TkKwParameterUnpack:
      return "TkKwParameterUnpack";
    case TkKwParameterHide:
      return "TkKwParameterHide";
    case TkKwParameterMerge:
      return "TkKwParameterMerge";
    case TkKwParameterId:
      return "TkKwParameterId";
    case TkKwParameterCaseSensitive:
      return "TkKwParameterCaseSensitive";
    case TkGrammarPropertyStart:
      return "TkGrammarPropertyStart";
    case TkGrammarPropertyWhitespace:
      return "TkGrammarPropertyWhitespace";
    case TkGrammarPropertySingleLineComment:
      return "TkGrammarPropertySingleLineComment";
    case TkGrammarPropertyMultiLineComment:
      return "TkGrammarPropertyMultiLineComment";
    case TkGrammarPropertyCaseSensitive:
      return "TkGrammarPropertyCaseSensitive";
    case NtGrammar:
      return "NtGrammar";
    case NtTerminalProduction:
      return "NtTerminalProduction";
    case NtTerminalParameter:
      return "NtTerminalParameter";
    case NtTerminalSequence:
      return "NtTerminalSequence";
    case NtTerminalChoices:
      return "NtTerminalChoices";
    case NtRuleProduction:
      return "NtRuleProduction";
    case NtRuleParameter:
      return "NtRuleParameter";
    case NtRuleSequence:
      return "NtRuleSequence";
    case NtRuleChoices:
      return "NtRuleChoices";
    case NtRepetition:
      return "NtTerminalRepetition";
    case NtRepetitionRange:
      return "NtTerminalRepetitionRange";
    case NtRange:
      return "NtTerminalRange";
    case NtGrammarProperty:
      return "NtGrammarProperty";
    case NtGrammarPropertyWhitespace:
      return "NtGrammarPropertyWhitespace";
    case NtGrammarPropertyWhitespaceChoices:
      return "NtGramarPropertyWhitespaceChoices";
    case NtGrammarPropertySingleLineComment:
      return "NtGrammarPropertySingleLineComment";
    case NtGrammarPropertySingleLineCommentChoices:
      return "NtGrammarPropertySingleLineCommentChoices";
    case NtGrammarPropertyMultiLineComment:
      return "NtGrammarPropertyMultiLineComment";
    case NtGrammarPropertyMultiLineCommentChoices:
      return "NtGrammarPropertyMultiLineCommentChoices";
    case NtGrammarPropertyCaseSensitive:
      return "NtGrammarPropertyCaseSensitive";
    case NtStringLiteralPair:
      return "NtStringLiteralPair";
    default:
      throw std::runtime_error("Invalid id");
  }
}
}  // namespace pmt::parserbuilder