/* Generated on: 2026-02-14 22:08:04 */
// clang-format off
"IntegerLiteral",
"ParameterHide",
"Plus",
"CharacterLiteral",
"BooleanLiteral",
"Question",
"ParameterId",
"Repetition",
"Star",
"Comma",
"ParameterDisplayName",
"Definition",
"StringLiteral",
"ParameterUnpack",
"ParameterMerge",
"Production",
"RepetitionRange",
"Eof",
"Epsilon",
"IdStringLiteral",
"Identifier",
"Choices",
"Sequence",
"Hidden",
"NegativeLookahead",
"PositiveLookahead",
"Charset",
"CharsetRange",
// clang-format on 